### ISSUE TITLE
This could not work for me on windows 11

### ISSUE THREAD

**Issue by dnlk-cyber** [kevinlang/phx_gen_tailwind#6]
[error] Task #PID<0.665.0> started from AtlasWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:4412: :erlang.open_port({:spawn_executable, 'c:/Program Files/nodejs/npx.cmd'}, [{:cd, "c:/Users/Lenovo/Desktop/side_projects/elixir_projects/atlas/assets"}, :stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["tailwindcss", "--input=css/app.css", "--output=../priv/static/assets/app.css", "--postcss", "--watch"]}])
    (elixir 1.12.2) lib/system.ex:1052: System.do_cmd/3
    (phoenix 1.6.2) lib/phoenix/endpoint/watcher.ex:36: Phoenix.Endpoint.Watcher.watch/2       
    (elixir 1.12.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["npx", ["tailwindcss", "--input=css/app.css", "--output=../priv/static/assets/app.css", "--postcss", "--watch", {:cd, "c:/Users/Lenovo/Desktop/side_projects/elixir_projects/atlas/assets"}]]
[error] Task #PID<0.666.0> started from AtlasWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:4412: :erlang.open_port({:spawn_executable, 'c:/Program Files/nodejs/npx.cmd'}, [{:cd, "c:/Users/Lenovo/Desktop/side_projects/elixir_projects/atlas/assets"}, :stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["tailwindcss", "--input=css/app.css", "--output=../priv/static/assets/app.css", "--postcss", "--watch"]}])
    (elixir 1.12.2) lib/system.ex:1052: System.do_cmd/3
    (phoenix 1.6.2) lib/phoenix/endpoint/watcher.ex:36: Phoenix.Endpoint.Watcher.watch/2       
    (elixir 1.12.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["npx", ["tailwindcss", "--input=css/app.css", "--output=../priv/static/assets/app.css", "--postcss", "--watch", {:cd, "c:/Users/Lenovo/Desktop/side_projects/elixir_projects/atlas/assets"}]]
[info] Running AtlasWeb.Endpoint with cowboy 2.9.0 at 127.0.0.1:4000 (http)
[info] Access AtlasWeb.Endpoint at http://localhost:4000
[error] Task #PID<0.792.0> started from AtlasWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:4412: :erlang.open_port({:spawn_executable, 'c:/Program Files/nodejs/npx.cmd'}, [{:cd, "c:/Users/Lenovo/Desktop/side_projects/elixir_projects/atlas/assets"}, :stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["tailwindcss", "--input=css/app.css", "--output=../priv/static/assets/app.css", "--postcss", "--watch"]}])
    (elixir 1.12.2) lib/system.ex:1052: System.do_cmd/3
    (phoenix 1.6.2) lib/phoenix/endpoint/watcher.ex:36: Phoenix.Endpoint.Watcher.watch/2       
    (elixir 1.12.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["npx", ["tailwindcss", "--input=css/app.css", "--output=../priv/static/assets/app.css", "--postcss", "--watch", {:cd, "c:/Users/Lenovo/Desktop/side_projects/elixir_projects/atlas/assets"}]]

**Comment by sajediqbal** [comment]
[error] Task #PID<0.655.0> started from PandaWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:4412: :erlang.open_port({:spawn_executable, 'c:/Program Files/nod
ejs/npx.cmd'}, [{:cd, "d:/Sajid Iqbal/panda/assets"}, :stderr_to_stdout, :use_st
dio, :exit_status, :binary, :hide, {:args, ["tailwindcss", "--input=css/app.css"
, "--output=../priv/static/assets/app.css", "--watch"]}])
    (elixir 1.12.3) lib/system.ex:1052: System.do_cmd/3
    (phoenix 1.6.2) lib/phoenix/endpoint/watcher.ex:36: Phoenix.Endpoint.Watcher
.watch/2
    (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["npx", ["tailwindcss", "--input=css/app.css", "--output=../priv/stati
c/assets/app.css", "--watch", {:cd, "d:/Sajid Iqbal/panda/assets"}]]
[error] Task #PID<0.656.0> started from PandaWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:4412: :erlang.open_port({:spawn_executable, 'c:/Program Files/nod
ejs/npx.cmd'}, [{:cd, "d:/Sajid Iqbal/panda/assets"}, :stderr_to_stdout, :use_st
dio, :exit_status, :binary, :hide, {:args, ["tailwindcss", "--input=css/app.css"
, "--output=../priv/static/assets/app.css", "--watch"]}])
    (elixir 1.12.3) lib/system.ex:1052: System.do_cmd/3
    (phoenix 1.6.2) lib/phoenix/endpoint/watcher.ex:36: Phoenix.Endpoint.Watcher
.watch/2
    (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["npx", ["tailwindcss", "--input=css/app.css", "--output=../priv/stati
c/assets/app.css", "--watch", {:cd, "d:/Sajid Iqbal/panda/assets"}]]
[error] Task #PID<0.657.0> started from PandaWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:4412: :erlang.open_port({:spawn_executable, 'c:/Program Files/nod
ejs/npx.cmd'}, [{:cd, "d:/Sajid Iqbal/panda/assets"}, :stderr_to_stdout, :use_st
dio, :exit_status, :binary, :hide, {:args, ["tailwindcss", "--input=css/app.css"
, "--output=../priv/static/assets/app.css", "--watch"]}])
    (elixir 1.12.3) lib/system.ex:1052: System.do_cmd/3
    (phoenix 1.6.2) lib/phoenix/endpoint/watcher.ex:36: Phoenix.Endpoint.Watcher
.watch/2
    (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["npx", ["tailwindcss", "--input=css/app.css", "--output=../priv/stati
c/assets/app.css", "--watch", {:cd, "d:/Sajid Iqbal/panda/assets"}]]
[error] Task #PID<0.658.0> started from PandaWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:4412: :erlang.open_port({:spawn_executable, 'c:/Program Files/nod
ejs/npx.cmd'}, [{:cd, "d:/Sajid Iqbal/panda/assets"}, :stderr_to_stdout, :use_st
dio, :exit_status, :binary, :hide, {:args, ["tailwindcss", "--input=css/app.css"
, "--output=../priv/static/assets/app.css", "--watch"]}])
    (elixir 1.12.3) lib/system.ex:1052: System.do_cmd/3
    (phoenix 1.6.2) lib/phoenix/endpoint/watcher.ex:36: Phoenix.Endpoint.Watcher
.watch/2
    (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["npx", ["tailwindcss", "--input=css/app.css", "--output=../priv/stati
c/assets/app.css", "--watch", {:cd, "d:/Sajid Iqbal/panda/assets"}]]
[error] Failed to start Ranch listener PandaWeb.Endpoint.HTTP in :ranch_tcp:list
en([cacerts: :..., key: :..., cert: :..., port: 4000, ip: {127, 0, 0, 1}]) for r
eason :eaddrinuse (address already in use)

[info] Running PandaWeb.Endpoint with cowboy 2.9.0 at 127.0.0.1:4000 (http)
[info] Access PandaWeb.Endpoint at http://localhost:4000
[error] Task #PID<0.791.0> started from PandaWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:4412: :erlang.open_port({:spawn_executable, 'c:/Program Files/nod
ejs/npx.cmd'}, [{:cd, "d:/Sajid Iqbal/panda/assets"}, :stderr_to_stdout, :use_st
dio, :exit_status, :binary, :hide, {:args, ["tailwindcss", "--input=css/app.css"
, "--output=../priv/static/assets/app.css", "--watch"]}])
    (elixir 1.12.3) lib/system.ex:1052: System.do_cmd/3
    (phoenix 1.6.2) lib/phoenix/endpoint/watcher.ex:36: Phoenix.Endpoint.Watcher
.watch/2
    (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["npx", ["tailwindcss", "--input=css/app.css", "--output=../priv/stati
c/assets/app.css", "--watch", {:cd, "d:/Sajid Iqbal/panda/assets"}]]
[error] Task #PID<0.792.0> started from PandaWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:4412: :erlang.open_port({:spawn_executable, 'c:/Program Files/nod
ejs/npx.cmd'}, [{:cd, "d:/Sajid Iqbal/panda/assets"}, :stderr_to_stdout, :use_st
dio, :exit_status, :binary, :hide, {:args, ["tailwindcss", "--input=css/app.css"
, "--output=../priv/static/assets/app.css", "--watch"]}])
    (elixir 1.12.3) lib/system.ex:1052: System.do_cmd/3
    (phoenix 1.6.2) lib/phoenix/endpoint/watcher.ex:36: Phoenix.Endpoint.Watcher
.watch/2
    (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["npx", ["tailwindcss", "--input=css/app.css", "--output=../priv/stati
c/assets/app.css", "--watch", {:cd, "d:/Sajid Iqbal/panda/assets"}]]
[error] Task #PID<0.793.0> started from PandaWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:4412: :erlang.open_port({:spawn_executable, 'c:/Program Files/nod
ejs/npx.cmd'}, [{:cd, "d:/Sajid Iqbal/panda/assets"}, :stderr_to_stdout, :use_st
dio, :exit_status, :binary, :hide, {:args, ["tailwindcss", "--input=css/app.css"
, "--output=../priv/static/assets/app.css", "--watch"]}])
    (elixir 1.12.3) lib/system.ex:1052: System.do_cmd/3
    (phoenix 1.6.2) lib/phoenix/endpoint/watcher.ex:36: Phoenix.Endpoint.Watcher
.watch/2
    (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["npx", ["tailwindcss", "--input=css/app.css", "--output=../priv/stati
c/assets/app.css", "--watch", {:cd, "d:/Sajid Iqbal/panda/assets"}]]
[error] Task #PID<0.794.0> started from PandaWeb.Endpoint terminating
** (stop) :eacces
    erlang.erl:4412: :erlang.open_port({:spawn_executable, 'c:/Program Files/nod
ejs/npx.cmd'}, [{:cd, "d:/Sajid Iqbal/panda/assets"}, :stderr_to_stdout, :use_st
dio, :exit_status, :binary, :hide, {:args, ["tailwindcss", "--input=css/app.css"
, "--output=../priv/static/assets/app.css", "--watch"]}])
    (elixir 1.12.3) lib/system.ex:1052: System.do_cmd/3
    (phoenix 1.6.2) lib/phoenix/endpoint/watcher.ex:36: Phoenix.Endpoint.Watcher
.watch/2
    (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["npx", ["tailwindcss", "--input=css/app.css", "--output=../priv/stati
c/assets/app.css", "--watch", {:cd, "d:/Sajid Iqbal/panda/assets"}]]
[error] Failed to start Ranch listener PandaWeb.Endpoint.HTTP in :ranch_tcp:list
en([cacerts: :..., key: :..., cert: :..., port: 4000, ip: {127, 0, 0, 1}]) for r
eason :eaddrinuse (address already in use)

[info] Application panda exited: shutdown

**Comment by JayPeet** [comment]
I have been getting the same issue on windows 10, unsure of the cause.

**Comment by matan1905** [comment]
For anyone dealing with this here is how I solved it:
according to this link: https://stackoverflow.com/questions/63096455/elixir-mix-stop-eacces-on-windows
the person just changed his npm.cmd to npm.bat
I solved my issue by changing npx.cmd to npx.bat

Other steps to solution that I tried that may have affected it:
1. tried to give full privileges to Everyone on every folder & npx.cmd
2. made sure port number isn't already in use

**Comment by dnlk-cyber** [comment]
Thanks
it worked for me also after changing npx.cmd to npx.bat
